Profile Folder/chrome/locale/es-CL/dtd/neterror.dtd

Mi venezolana reacción (Localize neterror.dtd for es-CL)

---

Profile Folder/chrome/locale/th-TH/dtd/neterror.dtd

Update Thai translation for about:dino

---

Profile Folder/chrome/locale/uk/dtd/gsettings.dtd

along with some other slight fixes here and there

Translated the newly-added parts of the file that were added to the Ukrainian locale

---

Profile Folder/chrome/locale/th-TH/dtd/gsettings.dtd

Update Thai translation for GTK+ icons option

---

Profile Folder/chrome/locale/pt-BR/dtd/gsettings.dtd

fix is basically something I did accidentally, but I discovered that there was a missing part of the translation for the system icons

Add missing pt-BR translation

---

Profile Folder/chrome/locale/vi-VN/dtd/gsettings.dtd
Profile Folder/chrome/locale/vi-VN/dtd/gwizard.dtd
Profile Folder/chrome/locale/vi-VN/properties/gm.properties
Profile Folder/chrome/locale/vi-VN/properties/gsettings.properties
Profile Folder/chrome/locale/vi-VN/properties/ntp.properties

Added some some missing translations, added new translations for the themes manager and tweaked some translations

Updated vi-VN translation

---

Profile Folder/chrome/locale/ro/dtd/gsettings.dtd
Profile Folder/chrome/locale/ro/properties/gsettings.properties

updated Romanian translation

---

Profile Folder/chrome/styles/partials/chrome/chrome-1/_tabs.scss

Yes, I can notice this 1 pixel offset.
Yes, it triggered me for weeks now.
Yes, I totally could just report it to the Discord and get it fixed.
Yes, I only decided to do this because I though it'll be fun to push a whole effing PR just for this (lol)
Yes, I have a very strong smile while writing this
And YES, I'm probably the only one to find this funny.
\*Awkward silence\*
*Cé pa façil tou lé joure.*

Smol accuracy fix

---

Profile Folder/chrome/locale/fr/dtd/gsettings.dtd

It just adds the new lines.
--
Off-topic : I have another branch called [Fixes-20241110](https://github.com/Kiki79250CoC/Geckium/tree/Fixes-20241110), it tries to fix one thing but I think the way I proceeded is kinda weird, so I committed them but with no plans of merging them (especially the second commit, the first one can be merged for sure, the second a bit less.)

Update for French locale

---

Profile Folder/chrome/locale/it/dtd/gsettings.dtd

Update missing IT locale strings

---

Profile Folder/chrome/locale/fr/dtd/gsettings.dtd
Profile Folder/chrome/locale/fr/properties/gsettings.properties

Update for French locale: Season 2 Episode 18

---

Profile Folder/chrome/locale/it/dtd/gsettings.dtd
Profile Folder/chrome/locale/it/properties/gsettings.properties

Update IT Locale with new strings

---

Profile Folder/chrome/locale/pl-PL/dtd/gsettings.dtd

i hope i didnt miss anything cause one commit (now discarded) was made on nearly 1am

new strings for pl-PL 

---

Profile Folder/chrome/locale/ro/dtd/gsettings.dtd

Romanian translation fix

---

Profile Folder/chrome/locale/tl-PH/dtd/gsettings.dtd
Profile Folder/chrome/locale/tl-PH/properties/gm.properties
Profile Folder/chrome/locale/tl-PH/properties/gsettings.properties

Issue with "[BUILT-IN]" string should be fixed now.

Fixing and updating tagalog translation

---

Profile Folder/chrome/locale/fr/dtd/gsettings.dtd

Update for French locale™: The baguette menace

---

Profile Folder/chrome/locale/it/dtd/gsettings.dtd
Profile Folder/chrome/locale/it/properties/gsettings.properties

Update IT locale

---

Profile Folder/chrome/locale/ru-RU/properties/gsettings.properties

I thought there were two lines to translate?

Update gsettings.properties (ru localise)

---

Profile Folder/chrome/locale/fr/dtd/gsettings.dtd
Profile Folder/chrome/locale/fr/properties/gsettings.properties

<sup>Finally I have realized that the removed spaces from your initial commit were normal spaces instead of non-break spaces, so I replaced them with proper non-break spaces.</sup>

Update for French locale™: Attack of the baguettes

---

Profile Folder/chrome/locale/ro/properties/ntp.properties

Romanian translation update

---

Profile Folder/chrome/locale/pt-BR/dtd/gm.dtd
Profile Folder/chrome/locale/pt-BR/dtd/gsettings.dtd
Profile Folder/chrome/locale/pt-BR/properties/gsettings.properties

Unfortunately I can't tell about the other one I've translated, but it seems to be an upcoming option for HiDPI mode, right?

Update pt-BR + two I missed

---

Profile Folder/chrome/locale/pl-PL/dtd/gsettings.dtd
Profile Folder/chrome/locale/pl-PL/properties/gsettings.properties
Profile Folder/chrome/locale/pl-PL/properties/ntp.properties

new pl-PL strings for geckium

---

Profile Folder/chrome/locale/fr/dtd/gm.dtd
Profile Folder/chrome/locale/fr/dtd/gsettings.dtd
Profile Folder/chrome/locale/fr/properties/gsettings.properties
Profile Folder/chrome/locale/fr/properties/ntp.properties

Update for French locale™: A new baguette
